[package]
name = "aoc-18"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { package = "aoc-core", path = "../aoc-core" }
