[workspace]
resolver = "2"
members = [
    "aoc",
    "aoc-core",
    "aoc-15",
    "aoc-16",
    "aoc-17",
    "aoc-18",
    "aoc-19",
    "aoc-20",
    "aoc-21",
    "aoc-22",
    "aoc-23",
    "aoc-24",
]
